version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=script.py
      - GOOGLE_API_KEY=asd
      - WA_TOKEN=
      - VERIFY_TOKEN=
      - NUMBER_ID=
      - FLASK_KEY=
